第4回課題
Ryo802701/RaiseTechJavaEx4 pull request #1
Opened 2022-08-15 12:47 UTC by Ryo802701

StreamAPIを使った処理です。

2022-08-15 12:53 UTC, Ryo802701 commented
![キャプチャ1](https://user-images.githubusercontent.com/102930186/184638401-23f5af5d-97ad-4e34-acb2-c2a0d1d986ea.PNG)

2022-08-15 13:36 UTC, YudaiNoda3576 requested changes
コメントしました〜

2022-08-15 13:36 UTC, YudaiNoda3576 commented on src/Main.java
> +		Employee shain1 = new Employee("鈴木", 45, "M", "管理部");
変数名は`employee1`の方が素直な気がします！

2022-08-15 13:36 UTC, YudaiNoda3576 commented on src/Main.java
> +		lstShain = new ArrayList<>(Arrays.asList(shain1, shain2, shain3, shain4, shain5, shain6, shain7));
こちらの方がすっきりする気がします！

```suggestion
        List<Employee> employeeList = Arrays.asList(shain1, shain2, shain3, shain4, shain5, shain6, shain7);
```

2022-08-15 13:36 UTC, YudaiNoda3576 commented on src/Main.java
> +		lstShain.stream().filter(x -> x.getDepartment() == "開発部").forEach(x -> System.out.println(x.getName() + "さん"));
Stringクラスは`equal`メソッドで比較するようにしてください〜
等値比較と等価比較についても調べて見てください！

2022-08-16 12:36 UTC, Ryo802701 commented
修正を行いました。

以下調べました。
・等値比較、等価比較
等値比較(==)は基本データ型の値の比較に使う。オブジェクト型に使うとメモリアドレスの比較になる（ただしStringは特殊）
等価比較はオブジェクトのequalsメソッドで比較する。equalsメソッドはオーバーライドして比較の仕方を定義し直すことができる。

・Stringの比較
別々のString変数でも同じ文字列リテラルだと同じメモリの場所を指すので==はtrueになり、
newでStringインスタンスを生成すると同じ文字列でも==ではfalseになる。
equalsメソッドを使った方がよい。

2022-08-17 00:11 UTC, YudaiNoda3576 reviewed
一点参考までにコメントしています！
修正問題なさそうなのでマージしてください！
お疲れ様でした:smile:

![LGTM](https://image.lgtmoon.dev/177361)

2022-08-17 00:11 UTC, YudaiNoda3576 commented on src/Main.java
> +							 .forEach(x -> System.out.println(x));
ここはメソッド参照でも書けますね！
```
        lstEmployee.stream().map(x -> x.getName() + "さんは" + (x.getSex().equals("M") ? "男性" : "女性") + "です。")
                .forEach(System.out::println);
```

2022-08-17 12:15 UTC, merged